version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${PHP_FPM_PORT:-9000}:9000
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
    nginx:
        image: nginx:alpine3.18-perl
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - ${APP_PORT:-8000}:8000
        networks:
            - app-network
        depends_on:
            - app
    pgsql:
        image: postgres:15
        volumes:
            - pgsql:/var/lib/postgresql/data
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    pgsql:
        driver: local
